os: osx
osx_image: xcode10.2
language: swift
script: xcodebuild clean build test -workspace Chuck\ Facts.xcworkspace -scheme "CI" -sdk iphonesimulator   ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO -destination 'platform=iOS Simulator,name=iPhone XÊ€,OS=12.2'
